#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 71
#define LARGE_STATE_COUNT 17
#define SYMBOL_COUNT 46
#define ALIAS_COUNT 0
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 7

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_DOT = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  anon_sym_COMMA = 5,
  anon_sym_DASH = 6,
  anon_sym_BANG = 7,
  anon_sym_PLUS_PLUS = 8,
  anon_sym_PIPE_PIPE = 9,
  anon_sym_AMP_AMP = 10,
  anon_sym_EQ_EQ = 11,
  anon_sym_BANG_EQ = 12,
  anon_sym_GT_EQ = 13,
  anon_sym_GT = 14,
  anon_sym_LT_EQ = 15,
  anon_sym_LT = 16,
  anon_sym_DQUOTE = 17,
  aux_sym_string_literal_token1 = 18,
  anon_sym_SQUOTE = 19,
  aux_sym_string_literal_token2 = 20,
  sym_escape_sequence = 21,
  sym_number_literal = 22,
  anon_sym_true = 23,
  anon_sym_false = 24,
  anon_sym_PIPE = 25,
  sym_comment = 26,
  sym__whitespace = 27,
  sym_source = 28,
  sym__expression = 29,
  sym_method_call = 30,
  sym_function_call = 31,
  sym_argument_list = 32,
  sym_unary_expression = 33,
  sym_binary_expression = 34,
  sym_literal = 35,
  sym_string_literal = 36,
  sym_boolean_literal = 37,
  sym_parenthesized_expression = 38,
  sym_lambda_expression = 39,
  sym_lambda_parameters = 40,
  aux_sym_source_repeat1 = 41,
  aux_sym_argument_list_repeat1 = 42,
  aux_sym_string_literal_repeat1 = 43,
  aux_sym_string_literal_repeat2 = 44,
  aux_sym_lambda_parameters_repeat1 = 45,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_DOT] = ".",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ",",
  [anon_sym_DASH] = "-",
  [anon_sym_BANG] = "!",
  [anon_sym_PLUS_PLUS] = "++",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_AMP_AMP] = "&&",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_GT] = ">",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_LT] = "<",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_literal_token1] = "string_literal_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_literal_token2] = "string_literal_token2",
  [sym_escape_sequence] = "escape_sequence",
  [sym_number_literal] = "number_literal",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_PIPE] = "|",
  [sym_comment] = "comment",
  [sym__whitespace] = "_whitespace",
  [sym_source] = "source",
  [sym__expression] = "_expression",
  [sym_method_call] = "method_call",
  [sym_function_call] = "function_call",
  [sym_argument_list] = "argument_list",
  [sym_unary_expression] = "unary_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_literal] = "literal",
  [sym_string_literal] = "string_literal",
  [sym_boolean_literal] = "boolean_literal",
  [sym_parenthesized_expression] = "parenthesized_expression",
  [sym_lambda_expression] = "lambda_expression",
  [sym_lambda_parameters] = "lambda_parameters",
  [aux_sym_source_repeat1] = "source_repeat1",
  [aux_sym_argument_list_repeat1] = "argument_list_repeat1",
  [aux_sym_string_literal_repeat1] = "string_literal_repeat1",
  [aux_sym_string_literal_repeat2] = "string_literal_repeat2",
  [aux_sym_lambda_parameters_repeat1] = "lambda_parameters_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_PLUS_PLUS] = anon_sym_PLUS_PLUS,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_literal_token1] = aux_sym_string_literal_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_literal_token2] = aux_sym_string_literal_token2,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_number_literal] = sym_number_literal,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym_comment] = sym_comment,
  [sym__whitespace] = sym__whitespace,
  [sym_source] = sym_source,
  [sym__expression] = sym__expression,
  [sym_method_call] = sym_method_call,
  [sym_function_call] = sym_function_call,
  [sym_argument_list] = sym_argument_list,
  [sym_unary_expression] = sym_unary_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_literal] = sym_literal,
  [sym_string_literal] = sym_string_literal,
  [sym_boolean_literal] = sym_boolean_literal,
  [sym_parenthesized_expression] = sym_parenthesized_expression,
  [sym_lambda_expression] = sym_lambda_expression,
  [sym_lambda_parameters] = sym_lambda_parameters,
  [aux_sym_source_repeat1] = aux_sym_source_repeat1,
  [aux_sym_argument_list_repeat1] = aux_sym_argument_list_repeat1,
  [aux_sym_string_literal_repeat1] = aux_sym_string_literal_repeat1,
  [aux_sym_string_literal_repeat2] = aux_sym_string_literal_repeat2,
  [aux_sym_lambda_parameters_repeat1] = aux_sym_lambda_parameters_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_number_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__whitespace] = {
    .visible = false,
    .named = true,
  },
  [sym_source] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_method_call] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthesized_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_lambda_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_lambda_parameters] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_literal_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_lambda_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_arguments = 1,
  field_body = 2,
  field_function = 3,
  field_left = 4,
  field_method = 5,
  field_object = 6,
  field_operator = 7,
  field_parameters = 8,
  field_right = 9,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arguments] = "arguments",
  [field_body] = "body",
  [field_function] = "function",
  [field_left] = "left",
  [field_method] = "method",
  [field_object] = "object",
  [field_operator] = "operator",
  [field_parameters] = "parameters",
  [field_right] = "right",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 3},
  [3] = {.index = 4, .length = 2},
  [4] = {.index = 6, .length = 2},
  [5] = {.index = 8, .length = 2},
  [6] = {.index = 10, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_function, 0},
  [1] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [4] =
    {field_arguments, 2},
    {field_function, 0},
  [6] =
    {field_body, 3},
    {field_parameters, 1},
  [8] =
    {field_method, 2},
    {field_object, 0},
  [10] =
    {field_arguments, 4},
    {field_method, 2},
    {field_object, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 28,
  [31] = 25,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 29,
  [36] = 34,
  [37] = 33,
  [38] = 27,
  [39] = 39,
  [40] = 17,
  [41] = 41,
  [42] = 19,
  [43] = 22,
  [44] = 20,
  [45] = 23,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 60,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 69,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(11);
      ADVANCE_MAP(
        '!', 18,
        '"', 31,
        '#', 35,
        '\'', 36,
        '(', 13,
        ')', 14,
        ',', 15,
        '-', 16,
        '.', 12,
        '<', 29,
        '>', 26,
        '\\', 37,
        '|', 43,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(31);
      if (lookahead == '#') ADVANCE(35);
      if (lookahead == '\\') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(39);
      if (lookahead == '\'') ADVANCE(36);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 3:
      if (lookahead == '&') ADVANCE(22);
      END_STATE();
    case 4:
      if (lookahead == '+') ADVANCE(20);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(23);
      END_STATE();
    case 6:
      ADVANCE_MAP(
        'x', 8,
        '"', 40,
        '0', 40,
        '\\', 40,
        'e', 40,
        'n', 40,
        'r', 40,
        't', 40,
      );
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(40);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(7);
      END_STATE();
    case 9:
      if (eof) ADVANCE(11);
      ADVANCE_MAP(
        '!', 18,
        '"', 31,
        '#', 45,
        '\'', 36,
        '(', 13,
        ')', 14,
        ',', 15,
        '-', 17,
        '|', 43,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 10:
      if (eof) ADVANCE(11);
      ADVANCE_MAP(
        '!', 19,
        '"', 31,
        '#', 45,
        '&', 3,
        '\'', 36,
        '(', 13,
        ')', 14,
        '+', 4,
        ',', 15,
        '-', 17,
        '.', 12,
        '<', 30,
        '=', 5,
        '>', 27,
        '|', 44,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(24);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_PLUS_PLUS);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(25);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(28);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(46);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(45);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_string_literal_token2);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_string_literal_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(46);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_string_literal_token2);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(45);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_number_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '|') ADVANCE(21);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym__whitespace);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(46);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'f') ADVANCE(1);
      if (lookahead == 't') ADVANCE(2);
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(3);
      END_STATE();
    case 2:
      if (lookahead == 'r') ADVANCE(4);
      END_STATE();
    case 3:
      if (lookahead == 'l') ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == 'u') ADVANCE(6);
      END_STATE();
    case 5:
      if (lookahead == 's') ADVANCE(7);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 9},
  [2] = {.lex_state = 10},
  [3] = {.lex_state = 10},
  [4] = {.lex_state = 10},
  [5] = {.lex_state = 10},
  [6] = {.lex_state = 10},
  [7] = {.lex_state = 10},
  [8] = {.lex_state = 10},
  [9] = {.lex_state = 10},
  [10] = {.lex_state = 10},
  [11] = {.lex_state = 10},
  [12] = {.lex_state = 10},
  [13] = {.lex_state = 9},
  [14] = {.lex_state = 9},
  [15] = {.lex_state = 9},
  [16] = {.lex_state = 9},
  [17] = {.lex_state = 10},
  [18] = {.lex_state = 10},
  [19] = {.lex_state = 10},
  [20] = {.lex_state = 10},
  [21] = {.lex_state = 9},
  [22] = {.lex_state = 10},
  [23] = {.lex_state = 10},
  [24] = {.lex_state = 9},
  [25] = {.lex_state = 9},
  [26] = {.lex_state = 9},
  [27] = {.lex_state = 9},
  [28] = {.lex_state = 9},
  [29] = {.lex_state = 9},
  [30] = {.lex_state = 9},
  [31] = {.lex_state = 9},
  [32] = {.lex_state = 9},
  [33] = {.lex_state = 9},
  [34] = {.lex_state = 9},
  [35] = {.lex_state = 9},
  [36] = {.lex_state = 9},
  [37] = {.lex_state = 9},
  [38] = {.lex_state = 9},
  [39] = {.lex_state = 10},
  [40] = {.lex_state = 10},
  [41] = {.lex_state = 10},
  [42] = {.lex_state = 10},
  [43] = {.lex_state = 10},
  [44] = {.lex_state = 10},
  [45] = {.lex_state = 10},
  [46] = {.lex_state = 10},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 9},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 9},
  [55] = {.lex_state = 9},
  [56] = {.lex_state = 9},
  [57] = {.lex_state = 9},
  [58] = {.lex_state = 9},
  [59] = {.lex_state = 9},
  [60] = {.lex_state = 9},
  [61] = {.lex_state = 9},
  [62] = {.lex_state = 9},
  [63] = {.lex_state = 9},
  [64] = {.lex_state = 9},
  [65] = {.lex_state = 9},
  [66] = {.lex_state = 9},
  [67] = {.lex_state = 9},
  [68] = {.lex_state = 9},
  [69] = {.lex_state = 9},
  [70] = {.lex_state = 9},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [aux_sym_string_literal_token1] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [aux_sym_string_literal_token2] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym__whitespace] = ACTIONS(3),
  },
  [1] = {
    [sym_source] = STATE(67),
    [sym__expression] = STATE(18),
    [sym_method_call] = STATE(18),
    [sym_function_call] = STATE(18),
    [sym_unary_expression] = STATE(18),
    [sym_binary_expression] = STATE(18),
    [sym_literal] = STATE(18),
    [sym_string_literal] = STATE(2),
    [sym_boolean_literal] = STATE(2),
    [sym_parenthesized_expression] = STATE(18),
    [sym_lambda_expression] = STATE(18),
    [aux_sym_source_repeat1] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_BANG] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [anon_sym_SQUOTE] = ACTIONS(17),
    [sym_number_literal] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [anon_sym_PIPE] = ACTIONS(23),
    [sym_comment] = ACTIONS(25),
    [sym__whitespace] = ACTIONS(25),
  },
  [2] = {
    [ts_builtin_sym_end] = ACTIONS(27),
    [sym_identifier] = ACTIONS(29),
    [anon_sym_DOT] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_RPAREN] = ACTIONS(27),
    [anon_sym_COMMA] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_BANG] = ACTIONS(29),
    [anon_sym_PLUS_PLUS] = ACTIONS(27),
    [anon_sym_PIPE_PIPE] = ACTIONS(27),
    [anon_sym_AMP_AMP] = ACTIONS(27),
    [anon_sym_EQ_EQ] = ACTIONS(27),
    [anon_sym_BANG_EQ] = ACTIONS(27),
    [anon_sym_GT_EQ] = ACTIONS(27),
    [anon_sym_GT] = ACTIONS(29),
    [anon_sym_LT_EQ] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(29),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [anon_sym_SQUOTE] = ACTIONS(27),
    [sym_number_literal] = ACTIONS(27),
    [anon_sym_true] = ACTIONS(29),
    [anon_sym_false] = ACTIONS(29),
    [anon_sym_PIPE] = ACTIONS(29),
    [sym_comment] = ACTIONS(25),
    [sym__whitespace] = ACTIONS(25),
  },
  [3] = {
    [ts_builtin_sym_end] = ACTIONS(31),
    [sym_identifier] = ACTIONS(33),
    [anon_sym_DOT] = ACTIONS(31),
    [anon_sym_LPAREN] = ACTIONS(31),
    [anon_sym_RPAREN] = ACTIONS(31),
    [anon_sym_COMMA] = ACTIONS(31),
    [anon_sym_DASH] = ACTIONS(33),
    [anon_sym_BANG] = ACTIONS(33),
    [anon_sym_PLUS_PLUS] = ACTIONS(31),
    [anon_sym_PIPE_PIPE] = ACTIONS(31),
    [anon_sym_AMP_AMP] = ACTIONS(31),
    [anon_sym_EQ_EQ] = ACTIONS(31),
    [anon_sym_BANG_EQ] = ACTIONS(31),
    [anon_sym_GT_EQ] = ACTIONS(31),
    [anon_sym_GT] = ACTIONS(33),
    [anon_sym_LT_EQ] = ACTIONS(31),
    [anon_sym_LT] = ACTIONS(33),
    [anon_sym_DQUOTE] = ACTIONS(31),
    [anon_sym_SQUOTE] = ACTIONS(31),
    [sym_number_literal] = ACTIONS(31),
    [anon_sym_true] = ACTIONS(33),
    [anon_sym_false] = ACTIONS(33),
    [anon_sym_PIPE] = ACTIONS(33),
    [sym_comment] = ACTIONS(25),
    [sym__whitespace] = ACTIONS(25),
  },
  [4] = {
    [ts_builtin_sym_end] = ACTIONS(35),
    [sym_identifier] = ACTIONS(37),
    [anon_sym_DOT] = ACTIONS(35),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_RPAREN] = ACTIONS(35),
    [anon_sym_COMMA] = ACTIONS(35),
    [anon_sym_DASH] = ACTIONS(37),
    [anon_sym_BANG] = ACTIONS(37),
    [anon_sym_PLUS_PLUS] = ACTIONS(35),
    [anon_sym_PIPE_PIPE] = ACTIONS(35),
    [anon_sym_AMP_AMP] = ACTIONS(35),
    [anon_sym_EQ_EQ] = ACTIONS(35),
    [anon_sym_BANG_EQ] = ACTIONS(35),
    [anon_sym_GT_EQ] = ACTIONS(35),
    [anon_sym_GT] = ACTIONS(37),
    [anon_sym_LT_EQ] = ACTIONS(35),
    [anon_sym_LT] = ACTIONS(37),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [anon_sym_SQUOTE] = ACTIONS(35),
    [sym_number_literal] = ACTIONS(35),
    [anon_sym_true] = ACTIONS(37),
    [anon_sym_false] = ACTIONS(37),
    [anon_sym_PIPE] = ACTIONS(37),
    [sym_comment] = ACTIONS(25),
    [sym__whitespace] = ACTIONS(25),
  },
  [5] = {
    [ts_builtin_sym_end] = ACTIONS(39),
    [sym_identifier] = ACTIONS(41),
    [anon_sym_DOT] = ACTIONS(43),
    [anon_sym_LPAREN] = ACTIONS(39),
    [anon_sym_RPAREN] = ACTIONS(39),
    [anon_sym_COMMA] = ACTIONS(39),
    [anon_sym_DASH] = ACTIONS(41),
    [anon_sym_BANG] = ACTIONS(41),
    [anon_sym_PLUS_PLUS] = ACTIONS(39),
    [anon_sym_PIPE_PIPE] = ACTIONS(39),
    [anon_sym_AMP_AMP] = ACTIONS(39),
    [anon_sym_EQ_EQ] = ACTIONS(39),
    [anon_sym_BANG_EQ] = ACTIONS(39),
    [anon_sym_GT_EQ] = ACTIONS(39),
    [anon_sym_GT] = ACTIONS(41),
    [anon_sym_LT_EQ] = ACTIONS(39),
    [anon_sym_LT] = ACTIONS(41),
    [anon_sym_DQUOTE] = ACTIONS(39),
    [anon_sym_SQUOTE] = ACTIONS(39),
    [sym_number_literal] = ACTIONS(39),
    [anon_sym_true] = ACTIONS(41),
    [anon_sym_false] = ACTIONS(41),
    [anon_sym_PIPE] = ACTIONS(41),
    [sym_comment] = ACTIONS(25),
    [sym__whitespace] = ACTIONS(25),
  },
  [6] = {
    [ts_builtin_sym_end] = ACTIONS(45),
    [sym_identifier] = ACTIONS(47),
    [anon_sym_DOT] = ACTIONS(45),
    [anon_sym_LPAREN] = ACTIONS(45),
    [anon_sym_RPAREN] = ACTIONS(45),
    [anon_sym_COMMA] = ACTIONS(45),
    [anon_sym_DASH] = ACTIONS(47),
    [anon_sym_BANG] = ACTIONS(47),
    [anon_sym_PLUS_PLUS] = ACTIONS(45),
    [anon_sym_PIPE_PIPE] = ACTIONS(45),
    [anon_sym_AMP_AMP] = ACTIONS(45),
    [anon_sym_EQ_EQ] = ACTIONS(45),
    [anon_sym_BANG_EQ] = ACTIONS(45),
    [anon_sym_GT_EQ] = ACTIONS(45),
    [anon_sym_GT] = ACTIONS(47),
    [anon_sym_LT_EQ] = ACTIONS(45),
    [anon_sym_LT] = ACTIONS(47),
    [anon_sym_DQUOTE] = ACTIONS(45),
    [anon_sym_SQUOTE] = ACTIONS(45),
    [sym_number_literal] = ACTIONS(45),
    [anon_sym_true] = ACTIONS(47),
    [anon_sym_false] = ACTIONS(47),
    [anon_sym_PIPE] = ACTIONS(47),
    [sym_comment] = ACTIONS(25),
    [sym__whitespace] = ACTIONS(25),
  },
  [7] = {
    [ts_builtin_sym_end] = ACTIONS(49),
    [sym_identifier] = ACTIONS(51),
    [anon_sym_DOT] = ACTIONS(49),
    [anon_sym_LPAREN] = ACTIONS(49),
    [anon_sym_RPAREN] = ACTIONS(49),
    [anon_sym_COMMA] = ACTIONS(49),
    [anon_sym_DASH] = ACTIONS(51),
    [anon_sym_BANG] = ACTIONS(51),
    [anon_sym_PLUS_PLUS] = ACTIONS(49),
    [anon_sym_PIPE_PIPE] = ACTIONS(49),
    [anon_sym_AMP_AMP] = ACTIONS(49),
    [anon_sym_EQ_EQ] = ACTIONS(49),
    [anon_sym_BANG_EQ] = ACTIONS(49),
    [anon_sym_GT_EQ] = ACTIONS(49),
    [anon_sym_GT] = ACTIONS(51),
    [anon_sym_LT_EQ] = ACTIONS(49),
    [anon_sym_LT] = ACTIONS(51),
    [anon_sym_DQUOTE] = ACTIONS(49),
    [anon_sym_SQUOTE] = ACTIONS(49),
    [sym_number_literal] = ACTIONS(49),
    [anon_sym_true] = ACTIONS(51),
    [anon_sym_false] = ACTIONS(51),
    [anon_sym_PIPE] = ACTIONS(51),
    [sym_comment] = ACTIONS(25),
    [sym__whitespace] = ACTIONS(25),
  },
  [8] = {
    [ts_builtin_sym_end] = ACTIONS(53),
    [sym_identifier] = ACTIONS(55),
    [anon_sym_DOT] = ACTIONS(53),
    [anon_sym_LPAREN] = ACTIONS(53),
    [anon_sym_RPAREN] = ACTIONS(53),
    [anon_sym_COMMA] = ACTIONS(53),
    [anon_sym_DASH] = ACTIONS(55),
    [anon_sym_BANG] = ACTIONS(55),
    [anon_sym_PLUS_PLUS] = ACTIONS(53),
    [anon_sym_PIPE_PIPE] = ACTIONS(53),
    [anon_sym_AMP_AMP] = ACTIONS(53),
    [anon_sym_EQ_EQ] = ACTIONS(53),
    [anon_sym_BANG_EQ] = ACTIONS(53),
    [anon_sym_GT_EQ] = ACTIONS(53),
    [anon_sym_GT] = ACTIONS(55),
    [anon_sym_LT_EQ] = ACTIONS(53),
    [anon_sym_LT] = ACTIONS(55),
    [anon_sym_DQUOTE] = ACTIONS(53),
    [anon_sym_SQUOTE] = ACTIONS(53),
    [sym_number_literal] = ACTIONS(53),
    [anon_sym_true] = ACTIONS(55),
    [anon_sym_false] = ACTIONS(55),
    [anon_sym_PIPE] = ACTIONS(55),
    [sym_comment] = ACTIONS(25),
    [sym__whitespace] = ACTIONS(25),
  },
  [9] = {
    [ts_builtin_sym_end] = ACTIONS(57),
    [sym_identifier] = ACTIONS(59),
    [anon_sym_DOT] = ACTIONS(57),
    [anon_sym_LPAREN] = ACTIONS(57),
    [anon_sym_RPAREN] = ACTIONS(57),
    [anon_sym_COMMA] = ACTIONS(57),
    [anon_sym_DASH] = ACTIONS(59),
    [anon_sym_BANG] = ACTIONS(59),
    [anon_sym_PLUS_PLUS] = ACTIONS(57),
    [anon_sym_PIPE_PIPE] = ACTIONS(57),
    [anon_sym_AMP_AMP] = ACTIONS(57),
    [anon_sym_EQ_EQ] = ACTIONS(57),
    [anon_sym_BANG_EQ] = ACTIONS(57),
    [anon_sym_GT_EQ] = ACTIONS(57),
    [anon_sym_GT] = ACTIONS(59),
    [anon_sym_LT_EQ] = ACTIONS(57),
    [anon_sym_LT] = ACTIONS(59),
    [anon_sym_DQUOTE] = ACTIONS(57),
    [anon_sym_SQUOTE] = ACTIONS(57),
    [sym_number_literal] = ACTIONS(57),
    [anon_sym_true] = ACTIONS(59),
    [anon_sym_false] = ACTIONS(59),
    [anon_sym_PIPE] = ACTIONS(59),
    [sym_comment] = ACTIONS(25),
    [sym__whitespace] = ACTIONS(25),
  },
  [10] = {
    [ts_builtin_sym_end] = ACTIONS(61),
    [sym_identifier] = ACTIONS(63),
    [anon_sym_DOT] = ACTIONS(61),
    [anon_sym_LPAREN] = ACTIONS(61),
    [anon_sym_RPAREN] = ACTIONS(61),
    [anon_sym_COMMA] = ACTIONS(61),
    [anon_sym_DASH] = ACTIONS(63),
    [anon_sym_BANG] = ACTIONS(63),
    [anon_sym_PLUS_PLUS] = ACTIONS(61),
    [anon_sym_PIPE_PIPE] = ACTIONS(61),
    [anon_sym_AMP_AMP] = ACTIONS(61),
    [anon_sym_EQ_EQ] = ACTIONS(61),
    [anon_sym_BANG_EQ] = ACTIONS(61),
    [anon_sym_GT_EQ] = ACTIONS(61),
    [anon_sym_GT] = ACTIONS(63),
    [anon_sym_LT_EQ] = ACTIONS(61),
    [anon_sym_LT] = ACTIONS(63),
    [anon_sym_DQUOTE] = ACTIONS(61),
    [anon_sym_SQUOTE] = ACTIONS(61),
    [sym_number_literal] = ACTIONS(61),
    [anon_sym_true] = ACTIONS(63),
    [anon_sym_false] = ACTIONS(63),
    [anon_sym_PIPE] = ACTIONS(63),
    [sym_comment] = ACTIONS(25),
    [sym__whitespace] = ACTIONS(25),
  },
  [11] = {
    [ts_builtin_sym_end] = ACTIONS(65),
    [sym_identifier] = ACTIONS(67),
    [anon_sym_DOT] = ACTIONS(43),
    [anon_sym_LPAREN] = ACTIONS(65),
    [anon_sym_RPAREN] = ACTIONS(65),
    [anon_sym_COMMA] = ACTIONS(65),
    [anon_sym_DASH] = ACTIONS(67),
    [anon_sym_BANG] = ACTIONS(67),
    [anon_sym_PLUS_PLUS] = ACTIONS(65),
    [anon_sym_PIPE_PIPE] = ACTIONS(65),
    [anon_sym_AMP_AMP] = ACTIONS(65),
    [anon_sym_EQ_EQ] = ACTIONS(65),
    [anon_sym_BANG_EQ] = ACTIONS(65),
    [anon_sym_GT_EQ] = ACTIONS(65),
    [anon_sym_GT] = ACTIONS(67),
    [anon_sym_LT_EQ] = ACTIONS(65),
    [anon_sym_LT] = ACTIONS(67),
    [anon_sym_DQUOTE] = ACTIONS(65),
    [anon_sym_SQUOTE] = ACTIONS(65),
    [sym_number_literal] = ACTIONS(65),
    [anon_sym_true] = ACTIONS(67),
    [anon_sym_false] = ACTIONS(67),
    [anon_sym_PIPE] = ACTIONS(67),
    [sym_comment] = ACTIONS(25),
    [sym__whitespace] = ACTIONS(25),
  },
  [12] = {
    [ts_builtin_sym_end] = ACTIONS(69),
    [sym_identifier] = ACTIONS(71),
    [anon_sym_DOT] = ACTIONS(69),
    [anon_sym_LPAREN] = ACTIONS(69),
    [anon_sym_RPAREN] = ACTIONS(69),
    [anon_sym_COMMA] = ACTIONS(69),
    [anon_sym_DASH] = ACTIONS(71),
    [anon_sym_BANG] = ACTIONS(71),
    [anon_sym_PLUS_PLUS] = ACTIONS(69),
    [anon_sym_PIPE_PIPE] = ACTIONS(69),
    [anon_sym_AMP_AMP] = ACTIONS(69),
    [anon_sym_EQ_EQ] = ACTIONS(69),
    [anon_sym_BANG_EQ] = ACTIONS(69),
    [anon_sym_GT_EQ] = ACTIONS(69),
    [anon_sym_GT] = ACTIONS(71),
    [anon_sym_LT_EQ] = ACTIONS(69),
    [anon_sym_LT] = ACTIONS(71),
    [anon_sym_DQUOTE] = ACTIONS(69),
    [anon_sym_SQUOTE] = ACTIONS(69),
    [sym_number_literal] = ACTIONS(69),
    [anon_sym_true] = ACTIONS(71),
    [anon_sym_false] = ACTIONS(71),
    [anon_sym_PIPE] = ACTIONS(71),
    [sym_comment] = ACTIONS(25),
    [sym__whitespace] = ACTIONS(25),
  },
  [13] = {
    [sym__expression] = STATE(18),
    [sym_method_call] = STATE(18),
    [sym_function_call] = STATE(18),
    [sym_unary_expression] = STATE(18),
    [sym_binary_expression] = STATE(18),
    [sym_literal] = STATE(18),
    [sym_string_literal] = STATE(2),
    [sym_boolean_literal] = STATE(2),
    [sym_parenthesized_expression] = STATE(18),
    [sym_lambda_expression] = STATE(18),
    [aux_sym_source_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(73),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_BANG] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [anon_sym_SQUOTE] = ACTIONS(17),
    [sym_number_literal] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [anon_sym_PIPE] = ACTIONS(23),
    [sym_comment] = ACTIONS(25),
    [sym__whitespace] = ACTIONS(25),
  },
  [14] = {
    [sym__expression] = STATE(39),
    [sym_method_call] = STATE(39),
    [sym_function_call] = STATE(39),
    [sym_argument_list] = STATE(68),
    [sym_unary_expression] = STATE(39),
    [sym_binary_expression] = STATE(39),
    [sym_literal] = STATE(39),
    [sym_string_literal] = STATE(2),
    [sym_boolean_literal] = STATE(2),
    [sym_parenthesized_expression] = STATE(39),
    [sym_lambda_expression] = STATE(39),
    [sym_identifier] = ACTIONS(75),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_RPAREN] = ACTIONS(77),
    [anon_sym_DASH] = ACTIONS(79),
    [anon_sym_BANG] = ACTIONS(81),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [anon_sym_SQUOTE] = ACTIONS(17),
    [sym_number_literal] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [anon_sym_PIPE] = ACTIONS(83),
    [sym_comment] = ACTIONS(25),
    [sym__whitespace] = ACTIONS(25),
  },
  [15] = {
    [sym__expression] = STATE(18),
    [sym_method_call] = STATE(18),
    [sym_function_call] = STATE(18),
    [sym_unary_expression] = STATE(18),
    [sym_binary_expression] = STATE(18),
    [sym_literal] = STATE(18),
    [sym_string_literal] = STATE(2),
    [sym_boolean_literal] = STATE(2),
    [sym_parenthesized_expression] = STATE(18),
    [sym_lambda_expression] = STATE(18),
    [aux_sym_source_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(85),
    [sym_identifier] = ACTIONS(87),
    [anon_sym_LPAREN] = ACTIONS(90),
    [anon_sym_DASH] = ACTIONS(93),
    [anon_sym_BANG] = ACTIONS(96),
    [anon_sym_DQUOTE] = ACTIONS(99),
    [anon_sym_SQUOTE] = ACTIONS(102),
    [sym_number_literal] = ACTIONS(105),
    [anon_sym_true] = ACTIONS(108),
    [anon_sym_false] = ACTIONS(108),
    [anon_sym_PIPE] = ACTIONS(111),
    [sym_comment] = ACTIONS(25),
    [sym__whitespace] = ACTIONS(25),
  },
  [16] = {
    [sym__expression] = STATE(39),
    [sym_method_call] = STATE(39),
    [sym_function_call] = STATE(39),
    [sym_argument_list] = STATE(66),
    [sym_unary_expression] = STATE(39),
    [sym_binary_expression] = STATE(39),
    [sym_literal] = STATE(39),
    [sym_string_literal] = STATE(2),
    [sym_boolean_literal] = STATE(2),
    [sym_parenthesized_expression] = STATE(39),
    [sym_lambda_expression] = STATE(39),
    [sym_identifier] = ACTIONS(75),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_RPAREN] = ACTIONS(114),
    [anon_sym_DASH] = ACTIONS(79),
    [anon_sym_BANG] = ACTIONS(81),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [anon_sym_SQUOTE] = ACTIONS(17),
    [sym_number_literal] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [anon_sym_PIPE] = ACTIONS(83),
    [sym_comment] = ACTIONS(25),
    [sym__whitespace] = ACTIONS(25),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(120), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
    ACTIONS(118), 8,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_PIPE,
    ACTIONS(116), 12,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_PLUS_PLUS,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number_literal,
  [32] = 9,
    ACTIONS(43), 1,
      anon_sym_DOT,
    ACTIONS(127), 1,
      anon_sym_PLUS_PLUS,
    ACTIONS(129), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(131), 1,
      anon_sym_AMP_AMP,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
    ACTIONS(135), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(133), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(123), 5,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number_literal,
    ACTIONS(125), 6,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_PIPE,
  [74] = 7,
    ACTIONS(43), 1,
      anon_sym_DOT,
    ACTIONS(131), 1,
      anon_sym_AMP_AMP,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
    ACTIONS(135), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(133), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(67), 6,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_PIPE,
    ACTIONS(65), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_PLUS_PLUS,
      anon_sym_PIPE_PIPE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number_literal,
  [112] = 6,
    ACTIONS(43), 1,
      anon_sym_DOT,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
    ACTIONS(135), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(133), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(67), 6,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_PIPE,
    ACTIONS(65), 8,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_PLUS_PLUS,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number_literal,
  [148] = 13,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      sym_number_literal,
    ACTIONS(75), 1,
      sym_identifier,
    ACTIONS(79), 1,
      anon_sym_DASH,
    ACTIONS(81), 1,
      anon_sym_BANG,
    ACTIONS(83), 1,
      anon_sym_PIPE,
    ACTIONS(137), 1,
      anon_sym_RPAREN,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
    STATE(2), 2,
      sym_string_literal,
      sym_boolean_literal,
    STATE(41), 8,
      sym__expression,
      sym_method_call,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_literal,
      sym_parenthesized_expression,
      sym_lambda_expression,
  [198] = 8,
    ACTIONS(43), 1,
      anon_sym_DOT,
    ACTIONS(129), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(131), 1,
      anon_sym_AMP_AMP,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
    ACTIONS(135), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(133), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(65), 6,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_PLUS_PLUS,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number_literal,
    ACTIONS(67), 6,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_PIPE,
  [238] = 9,
    ACTIONS(43), 1,
      anon_sym_DOT,
    ACTIONS(127), 1,
      anon_sym_PLUS_PLUS,
    ACTIONS(129), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(131), 1,
      anon_sym_AMP_AMP,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
    ACTIONS(135), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(133), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(139), 5,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_number_literal,
    ACTIONS(141), 6,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_PIPE,
  [280] = 13,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      sym_number_literal,
    ACTIONS(75), 1,
      sym_identifier,
    ACTIONS(79), 1,
      anon_sym_DASH,
    ACTIONS(81), 1,
      anon_sym_BANG,
    ACTIONS(83), 1,
      anon_sym_PIPE,
    ACTIONS(143), 1,
      anon_sym_RPAREN,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
    STATE(2), 2,
      sym_string_literal,
      sym_boolean_literal,
    STATE(41), 8,
      sym__expression,
      sym_method_call,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_literal,
      sym_parenthesized_expression,
      sym_lambda_expression,
  [330] = 12,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      sym_number_literal,
    ACTIONS(75), 1,
      sym_identifier,
    ACTIONS(79), 1,
      anon_sym_DASH,
    ACTIONS(81), 1,
      anon_sym_BANG,
    ACTIONS(83), 1,
      anon_sym_PIPE,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
    STATE(2), 2,
      sym_string_literal,
      sym_boolean_literal,
    STATE(42), 8,
      sym__expression,
      sym_method_call,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_literal,
      sym_parenthesized_expression,
      sym_lambda_expression,
  [377] = 12,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      sym_number_literal,
    ACTIONS(75), 1,
      sym_identifier,
    ACTIONS(79), 1,
      anon_sym_DASH,
    ACTIONS(81), 1,
      anon_sym_BANG,
    ACTIONS(83), 1,
      anon_sym_PIPE,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
    STATE(2), 2,
      sym_string_literal,
      sym_boolean_literal,
    STATE(46), 8,
      sym__expression,
      sym_method_call,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_literal,
      sym_parenthesized_expression,
      sym_lambda_expression,
  [424] = 12,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_BANG,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      sym_number_literal,
    ACTIONS(23), 1,
      anon_sym_PIPE,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
    STATE(2), 2,
      sym_string_literal,
      sym_boolean_literal,
    STATE(5), 8,
      sym__expression,
      sym_method_call,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_literal,
      sym_parenthesized_expression,
      sym_lambda_expression,
  [471] = 12,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_BANG,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      sym_number_literal,
    ACTIONS(23), 1,
      anon_sym_PIPE,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
    STATE(2), 2,
      sym_string_literal,
      sym_boolean_literal,
    STATE(23), 8,
      sym__expression,
      sym_method_call,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_literal,
      sym_parenthesized_expression,
      sym_lambda_expression,
  [518] = 12,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_BANG,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      sym_number_literal,
    ACTIONS(23), 1,
      anon_sym_PIPE,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
    STATE(2), 2,
      sym_string_literal,
      sym_boolean_literal,
    STATE(22), 8,
      sym__expression,
      sym_method_call,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_literal,
      sym_parenthesized_expression,
      sym_lambda_expression,
  [565] = 12,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      sym_number_literal,
    ACTIONS(75), 1,
      sym_identifier,
    ACTIONS(79), 1,
      anon_sym_DASH,
    ACTIONS(81), 1,
      anon_sym_BANG,
    ACTIONS(83), 1,
      anon_sym_PIPE,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
    STATE(2), 2,
      sym_string_literal,
      sym_boolean_literal,
    STATE(45), 8,
      sym__expression,
      sym_method_call,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_literal,
      sym_parenthesized_expression,
      sym_lambda_expression,
  [612] = 12,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_BANG,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      sym_number_literal,
    ACTIONS(23), 1,
      anon_sym_PIPE,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
    STATE(2), 2,
      sym_string_literal,
      sym_boolean_literal,
    STATE(19), 8,
      sym__expression,
      sym_method_call,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_literal,
      sym_parenthesized_expression,
      sym_lambda_expression,
  [659] = 12,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      sym_number_literal,
    ACTIONS(75), 1,
      sym_identifier,
    ACTIONS(79), 1,
      anon_sym_DASH,
    ACTIONS(81), 1,
      anon_sym_BANG,
    ACTIONS(83), 1,
      anon_sym_PIPE,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
    STATE(2), 2,
      sym_string_literal,
      sym_boolean_literal,
    STATE(41), 8,
      sym__expression,
      sym_method_call,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_literal,
      sym_parenthesized_expression,
      sym_lambda_expression,
  [706] = 12,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_BANG,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      sym_number_literal,
    ACTIONS(23), 1,
      anon_sym_PIPE,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
    STATE(2), 2,
      sym_string_literal,
      sym_boolean_literal,
    STATE(20), 8,
      sym__expression,
      sym_method_call,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_literal,
      sym_parenthesized_expression,
      sym_lambda_expression,
  [753] = 12,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      sym_number_literal,
    ACTIONS(75), 1,
      sym_identifier,
    ACTIONS(79), 1,
      anon_sym_DASH,
    ACTIONS(81), 1,
      anon_sym_BANG,
    ACTIONS(83), 1,
      anon_sym_PIPE,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
    STATE(2), 2,
      sym_string_literal,
      sym_boolean_literal,
    STATE(11), 8,
      sym__expression,
      sym_method_call,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_literal,
      sym_parenthesized_expression,
      sym_lambda_expression,
  [800] = 12,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      sym_number_literal,
    ACTIONS(75), 1,
      sym_identifier,
    ACTIONS(79), 1,
      anon_sym_DASH,
    ACTIONS(81), 1,
      anon_sym_BANG,
    ACTIONS(83), 1,
      anon_sym_PIPE,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
    STATE(2), 2,
      sym_string_literal,
      sym_boolean_literal,
    STATE(43), 8,
      sym__expression,
      sym_method_call,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_literal,
      sym_parenthesized_expression,
      sym_lambda_expression,
  [847] = 12,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_BANG,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      sym_number_literal,
    ACTIONS(23), 1,
      anon_sym_PIPE,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
    STATE(2), 2,
      sym_string_literal,
      sym_boolean_literal,
    STATE(11), 8,
      sym__expression,
      sym_method_call,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_literal,
      sym_parenthesized_expression,
      sym_lambda_expression,
  [894] = 12,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      sym_number_literal,
    ACTIONS(75), 1,
      sym_identifier,
    ACTIONS(79), 1,
      anon_sym_DASH,
    ACTIONS(81), 1,
      anon_sym_BANG,
    ACTIONS(83), 1,
      anon_sym_PIPE,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
    STATE(2), 2,
      sym_string_literal,
      sym_boolean_literal,
    STATE(44), 8,
      sym__expression,
      sym_method_call,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_literal,
      sym_parenthesized_expression,
      sym_lambda_expression,
  [941] = 12,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_SQUOTE,
    ACTIONS(19), 1,
      sym_number_literal,
    ACTIONS(75), 1,
      sym_identifier,
    ACTIONS(79), 1,
      anon_sym_DASH,
    ACTIONS(81), 1,
      anon_sym_BANG,
    ACTIONS(83), 1,
      anon_sym_PIPE,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
    STATE(2), 2,
      sym_string_literal,
      sym_boolean_literal,
    STATE(5), 8,
      sym__expression,
      sym_method_call,
      sym_function_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_literal,
      sym_parenthesized_expression,
      sym_lambda_expression,
  [988] = 10,
    ACTIONS(43), 1,
      anon_sym_DOT,
    ACTIONS(145), 1,
      anon_sym_RPAREN,
    ACTIONS(147), 1,
      anon_sym_COMMA,
    ACTIONS(149), 1,
      anon_sym_PLUS_PLUS,
    ACTIONS(151), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(153), 1,
      anon_sym_AMP_AMP,
    STATE(54), 1,
      aux_sym_argument_list_repeat1,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
    ACTIONS(157), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(155), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1024] = 4,
    ACTIONS(159), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
    ACTIONS(118), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(116), 10,
      anon_sym_DOT,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS_PLUS,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1048] = 8,
    ACTIONS(43), 1,
      anon_sym_DOT,
    ACTIONS(149), 1,
      anon_sym_PLUS_PLUS,
    ACTIONS(151), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(153), 1,
      anon_sym_AMP_AMP,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
    ACTIONS(157), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(161), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(155), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1079] = 6,
    ACTIONS(43), 1,
      anon_sym_DOT,
    ACTIONS(153), 1,
      anon_sym_AMP_AMP,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
    ACTIONS(157), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(65), 4,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS_PLUS,
      anon_sym_PIPE_PIPE,
    ACTIONS(155), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1106] = 7,
    ACTIONS(43), 1,
      anon_sym_DOT,
    ACTIONS(151), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(153), 1,
      anon_sym_AMP_AMP,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
    ACTIONS(157), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(65), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS_PLUS,
    ACTIONS(155), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1135] = 5,
    ACTIONS(43), 1,
      anon_sym_DOT,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
    ACTIONS(157), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(155), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(65), 5,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PLUS_PLUS,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [1160] = 8,
    ACTIONS(43), 1,
      anon_sym_DOT,
    ACTIONS(149), 1,
      anon_sym_PLUS_PLUS,
    ACTIONS(151), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(153), 1,
      anon_sym_AMP_AMP,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
    ACTIONS(139), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(157), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(155), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1191] = 8,
    ACTIONS(43), 1,
      anon_sym_DOT,
    ACTIONS(149), 1,
      anon_sym_PLUS_PLUS,
    ACTIONS(151), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(153), 1,
      anon_sym_AMP_AMP,
    ACTIONS(163), 1,
      anon_sym_RPAREN,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
    ACTIONS(157), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(155), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [1221] = 5,
    ACTIONS(165), 1,
      anon_sym_DQUOTE,
    ACTIONS(167), 1,
      aux_sym_string_literal_token1,
    ACTIONS(170), 1,
      sym_escape_sequence,
    STATE(47), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
  [1238] = 5,
    ACTIONS(173), 1,
      anon_sym_DQUOTE,
    ACTIONS(175), 1,
      aux_sym_string_literal_token1,
    ACTIONS(177), 1,
      sym_escape_sequence,
    STATE(47), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
  [1255] = 5,
    ACTIONS(179), 1,
      anon_sym_DQUOTE,
    ACTIONS(181), 1,
      aux_sym_string_literal_token1,
    ACTIONS(183), 1,
      sym_escape_sequence,
    STATE(48), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
  [1272] = 4,
    ACTIONS(179), 1,
      anon_sym_SQUOTE,
    ACTIONS(185), 1,
      aux_sym_string_literal_token2,
    STATE(53), 1,
      aux_sym_string_literal_repeat2,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
  [1286] = 4,
    ACTIONS(187), 1,
      anon_sym_SQUOTE,
    ACTIONS(189), 1,
      aux_sym_string_literal_token2,
    STATE(51), 1,
      aux_sym_string_literal_repeat2,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
  [1300] = 4,
    ACTIONS(192), 1,
      anon_sym_COMMA,
    ACTIONS(194), 1,
      anon_sym_PIPE,
    STATE(56), 1,
      aux_sym_lambda_parameters_repeat1,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
  [1314] = 4,
    ACTIONS(173), 1,
      anon_sym_SQUOTE,
    ACTIONS(196), 1,
      aux_sym_string_literal_token2,
    STATE(51), 1,
      aux_sym_string_literal_repeat2,
    ACTIONS(3), 2,
      sym_comment,
      sym__whitespace,
  [1328] = 4,
    ACTIONS(143), 1,
      anon_sym_RPAREN,
    ACTIONS(198), 1,
      anon_sym_COMMA,
    STATE(57), 1,
      aux_sym_argument_list_repeat1,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
  [1342] = 4,
    ACTIONS(200), 1,
      anon_sym_COMMA,
    ACTIONS(202), 1,
      anon_sym_PIPE,
    STATE(52), 1,
      aux_sym_lambda_parameters_repeat1,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
  [1356] = 4,
    ACTIONS(204), 1,
      anon_sym_COMMA,
    ACTIONS(207), 1,
      anon_sym_PIPE,
    STATE(56), 1,
      aux_sym_lambda_parameters_repeat1,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
  [1370] = 4,
    ACTIONS(161), 1,
      anon_sym_RPAREN,
    ACTIONS(209), 1,
      anon_sym_COMMA,
    STATE(57), 1,
      aux_sym_argument_list_repeat1,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
  [1384] = 3,
    ACTIONS(212), 1,
      sym_identifier,
    ACTIONS(214), 1,
      anon_sym_PIPE,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
  [1395] = 3,
    ACTIONS(194), 1,
      anon_sym_PIPE,
    ACTIONS(212), 1,
      sym_identifier,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
  [1406] = 3,
    ACTIONS(216), 1,
      sym_identifier,
    STATE(69), 1,
      sym_lambda_parameters,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
  [1417] = 2,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
    ACTIONS(207), 2,
      anon_sym_COMMA,
      anon_sym_PIPE,
  [1426] = 3,
    ACTIONS(216), 1,
      sym_identifier,
    STATE(70), 1,
      sym_lambda_parameters,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
  [1437] = 2,
    ACTIONS(218), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
  [1445] = 2,
    ACTIONS(220), 1,
      sym_identifier,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
  [1453] = 2,
    ACTIONS(212), 1,
      sym_identifier,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
  [1461] = 2,
    ACTIONS(222), 1,
      anon_sym_RPAREN,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
  [1469] = 2,
    ACTIONS(224), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
  [1477] = 2,
    ACTIONS(226), 1,
      anon_sym_RPAREN,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
  [1485] = 2,
    ACTIONS(228), 1,
      anon_sym_PIPE,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
  [1493] = 2,
    ACTIONS(230), 1,
      anon_sym_PIPE,
    ACTIONS(25), 2,
      sym_comment,
      sym__whitespace,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(17)] = 0,
  [SMALL_STATE(18)] = 32,
  [SMALL_STATE(19)] = 74,
  [SMALL_STATE(20)] = 112,
  [SMALL_STATE(21)] = 148,
  [SMALL_STATE(22)] = 198,
  [SMALL_STATE(23)] = 238,
  [SMALL_STATE(24)] = 280,
  [SMALL_STATE(25)] = 330,
  [SMALL_STATE(26)] = 377,
  [SMALL_STATE(27)] = 424,
  [SMALL_STATE(28)] = 471,
  [SMALL_STATE(29)] = 518,
  [SMALL_STATE(30)] = 565,
  [SMALL_STATE(31)] = 612,
  [SMALL_STATE(32)] = 659,
  [SMALL_STATE(33)] = 706,
  [SMALL_STATE(34)] = 753,
  [SMALL_STATE(35)] = 800,
  [SMALL_STATE(36)] = 847,
  [SMALL_STATE(37)] = 894,
  [SMALL_STATE(38)] = 941,
  [SMALL_STATE(39)] = 988,
  [SMALL_STATE(40)] = 1024,
  [SMALL_STATE(41)] = 1048,
  [SMALL_STATE(42)] = 1079,
  [SMALL_STATE(43)] = 1106,
  [SMALL_STATE(44)] = 1135,
  [SMALL_STATE(45)] = 1160,
  [SMALL_STATE(46)] = 1191,
  [SMALL_STATE(47)] = 1221,
  [SMALL_STATE(48)] = 1238,
  [SMALL_STATE(49)] = 1255,
  [SMALL_STATE(50)] = 1272,
  [SMALL_STATE(51)] = 1286,
  [SMALL_STATE(52)] = 1300,
  [SMALL_STATE(53)] = 1314,
  [SMALL_STATE(54)] = 1328,
  [SMALL_STATE(55)] = 1342,
  [SMALL_STATE(56)] = 1356,
  [SMALL_STATE(57)] = 1370,
  [SMALL_STATE(58)] = 1384,
  [SMALL_STATE(59)] = 1395,
  [SMALL_STATE(60)] = 1406,
  [SMALL_STATE(61)] = 1417,
  [SMALL_STATE(62)] = 1426,
  [SMALL_STATE(63)] = 1437,
  [SMALL_STATE(64)] = 1445,
  [SMALL_STATE(65)] = 1453,
  [SMALL_STATE(66)] = 1461,
  [SMALL_STATE(67)] = 1469,
  [SMALL_STATE(68)] = 1477,
  [SMALL_STATE(69)] = 1485,
  [SMALL_STATE(70)] = 1493,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 2, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 2, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 2, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 3, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_call, 5, 0, 5),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_method_call, 5, 0, 5),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_call, 6, 0, 6),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_method_call, 6, 0, 6),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, 0, 3),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 4, 0, 3),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 2),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 2),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, 0, 1),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 3, 0, 1),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0),
  [87] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [93] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [105] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [108] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [111] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1, 0, 0),
  [120] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0), SHIFT(14),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 1, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 1, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 3, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lambda_expression, 4, 0, 4),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lambda_expression, 4, 0, 4),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0),
  [167] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [170] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [175] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [185] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_literal_repeat2, 2, 0, 0),
  [189] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat2, 2, 0, 0), SHIFT_REPEAT(51),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lambda_parameters, 2, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lambda_parameters, 1, 0, 0),
  [204] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_lambda_parameters_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_lambda_parameters_repeat1, 2, 0, 0),
  [209] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lambda_parameters, 3, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [224] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_jj_template(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
